export const docsByLanguage = {
  en: [
    {id:'introduction',title:'Introduction to Aether',html:`<p>Aether discovers usable Cloudflare endpoints and creates a local SOCKS5 proxy through MASQUE, WireGuard, or gool. Firstham AetherGui is a Windows frontend for the official Aether core. It starts the bundled core safely, passes supported settings, shows status and logs, and stops the process cleanly.</p><aside><b>Proxy, not a system-wide VPN</b><p>Configure each application to use <code>127.0.0.1:1819</code>, or route applications through v2rayN or Proxifier.</p></aside>`},
    {id:'how',title:'How Aether works',html:`<p>Connect validates the profile and starts <code>aether.exe</code> as a hidden child process. Aether scans for an endpoint, establishes the selected tunnel, and listens locally for SOCKS5 traffic.</p><div class="doc-flow"><span>Your application</span><i>→</i><b>SOCKS5<br><small>127.0.0.1:1819</small></b><i>→</i><span>Aether tunnel</span><i>→</i><span>Internet</span></div><p>Enable proxy or remote DNS in the client when available so name resolution follows the same route.</p>`},
    {id:'interface',title:'Application sections',html:`<ul><li><b>Connection:</b> state, Connect/Disconnect, endpoint, proxy address, elapsed time, and the compact profile.</li><li><b>Advanced Settings:</b> IP mode, obfuscation, listener, endpoint, timeouts, safety switches, and config paths.</li><li><b>Diagnostics:</b> connection verification, Cloudflare trace, and live core logs.</li><li><b>User guide:</b> searchable bilingual documentation.</li><li><b>About:</b> version, attribution, update, and Telegram links.</li><li><b>System tray:</b> Show, Connect, Disconnect, and Exit. Closing the window hides it without breaking an active proxy.</li></ul>`},
    {id:'setup',title:'First-time setup',html:`<ol><li>Install the latest x64 Setup from this project's GitHub Releases page.</li><li>Launch Firstham AetherGui and choose English or Persian.</li><li>Keep <b>MASQUE</b>, <b>Balanced</b>, and <b>HTTP/3</b>.</li><li>Press <b>Connect</b> and wait for Connected.</li><li>Open <b>Diagnostics</b> and run Verify connection.</li><li>Configure your application as SOCKS5 with host <code>127.0.0.1</code> and port <code>1819</code>.</li></ol>`},
    {id:'states',title:'Connection states',html:`<div class="state-guide"><p><i class="state-dot disconnected"></i><b>Disconnected</b> — no proxy is running.</p><p><i class="state-dot scanning"></i><b>Scanning</b> — searching for a healthy endpoint.</p><p><i class="state-dot connecting"></i><b>Connecting</b> — negotiating the tunnel.</p><p><i class="state-dot connected"></i><b>Connected</b> — SOCKS5 is ready.</p><p><i class="state-dot reconnecting"></i><b>Reconnecting</b> — restoring a lost route.</p><p><i class="state-dot error"></i><b>Error</b> — inspect Diagnostics and try another profile.</p></div>`},
    {id:'protocols',title:'MASQUE, WireGuard, and gool',html:`<div class="doc-cards"><div><b>MASQUE · recommended</b><p>HTTP-based tunneling. Start with HTTP/3 and use HTTP/2 when UDP is blocked.</p></div><div><b>WireGuard</b><p>A lightweight UDP tunnel that may perform well when WireGuard traffic is usable.</p></div><div><b>gool</b><p>Aether's WARP-in-WARP alternative for networks where other profiles are unreliable.</p></div></div><p>No protocol wins on every network. Try MASQUE HTTP/2 before changing away from MASQUE.</p>`},
    {id:'transport',title:'HTTP/3 versus HTTP/2',html:`<table><thead><tr><th></th><th>HTTP/3</th><th>HTTP/2</th></tr></thead><tbody><tr><th>Transport</th><td>QUIC / UDP</td><td>TCP</td></tr><tr><th>Use first</th><td>Yes</td><td>When UDP fails</td></tr><tr><th>Aether value</th><td><code>AETHER_MASQUE_HTTP2=0</code></td><td><code>AETHER_MASQUE_HTTP2=1</code></td></tr></tbody></table>`},
    {id:'scan',title:'Scan and IP modes',html:`<ul><li><b>Turbo:</b> quickest discovery on a healthy network.</li><li><b>Balanced:</b> recommended balance of speed and coverage.</li><li><b>Thorough:</b> wider, slower search when Balanced finds nothing.</li><li><b>Stealth:</b> conservative scan pattern for sensitive networks.</li></ul><p>Use IPv4 by default. Choose IPv6 only with reliable native IPv6; Both expands coverage and can increase scan time.</p>`},
    {id:'obfuscation',title:'Obfuscation profiles',html:`<p>Obfuscation changes observable traffic patterns. The GUI only shows profiles valid for the selected protocol.</p><ul><li><b>MASQUE:</b> Firewall (recommended), GFW, Off.</li><li><b>WireGuard and gool:</b> Balanced (recommended), Aggressive, Light, Off.</li></ul><p>Aggressive modes add overhead. Increase obfuscation only when the recommended profile fails.</p>`},
    {id:'advanced',title:'Advanced Settings and Watchdog',html:`<ul><li><b>SOCKS5 listener:</b> keep <code>127.0.0.1:1819</code>. A non-local address exposes the proxy to the network.</li><li><b>Custom endpoint:</b> an exact <code>IP:port</code>; leave empty for scanning.</li><li><b>Keepalive:</b> WireGuard keepalive interval; 5 seconds is recommended.</li><li><b>Stall timeout:</b> time before a connection attempt is considered stuck; 90 seconds is recommended.</li><li><b>Watchdog:</b> safely stops a stuck core process. Keep enabled.</li><li><b>Quick reconnect:</b> tries the last verified endpoint first.</li><li><b>Configuration paths:</b> optional Aether-compatible files. The GUI stores paths, not private keys.</li></ul>`},
    {id:'environment',title:'Environment variables',html:`<table><thead><tr><th>Variable</th><th>GUI setting</th></tr></thead><tbody><tr><td><code>AETHER_PROTOCOL</code></td><td>Protocol</td></tr><tr><td><code>AETHER_SCAN</code></td><td>Scan mode</td></tr><tr><td><code>AETHER_IP</code></td><td>IP scan</td></tr><tr><td><code>AETHER_NOIZE</code></td><td>Obfuscation</td></tr><tr><td><code>AETHER_SOCKS</code></td><td>SOCKS5 listener</td></tr><tr><td><code>AETHER_MASQUE_HTTP2</code></td><td>MASQUE transport</td></tr><tr><td><code>AETHER_PEER / AETHER_WG_PEER</code></td><td>Custom endpoint</td></tr><tr><td><code>AETHER_WG_KEEPALIVE</code></td><td>Keepalive</td></tr><tr><td><code>AETHER_QUICK_RECONNECT</code></td><td>Quick reconnect</td></tr><tr><td><code>AETHER_CONFIG</code></td><td>Base config</td></tr><tr><td><code>AETHER_WG_CONFIG</code></td><td>WireGuard config</td></tr><tr><td><code>AETHER_MASQUE_CONFIG</code></td><td>MASQUE config</td></tr></tbody></table>`},
    {id:'v2rayn',title:'Configure v2rayN',html:`<ol><li>Connect Aether and wait for Connected.</li><li>In v2rayN, add a SOCKS server/profile.</li><li>Set Remarks to <code>Aether</code>, Address to <code>127.0.0.1</code>, Port to <code>1819</code>, and leave credentials empty.</li><li>Save and select it, or use its alias as a Front Proxy for another v2rayN node.</li><li>If TUN is enabled, add Direct/bypass rules for <code>aether-gui.exe</code> and <code>aether.exe</code>.</li></ol><div class="doc-route"><span>Application</span><i>→</i><span>v2rayN</span><i>→</i><b>Aether SOCKS5</b><i>→</i><span>Internet</span></div><aside><b>Avoid loops</b><p>Do not make Aether both the input and output of the same route.</p></aside>`},
    {id:'proxifier',title:'Configure Proxifier',html:`<ol><li>Connect Aether.</li><li>Open <b>Profile → Proxy Servers → Add</b>.</li><li>Address: <code>127.0.0.1</code>; Port: <code>1819</code>; Protocol: <b>SOCKS Version 5</b>; Authentication: Off.</li><li>Press Check and save.</li><li>In Proxification Rules, create a top <b>Direct</b> rule for <code>aether-gui.exe; aether.exe</code>.</li><li>Add the desired applications below it and select the Aether proxy. Keep Localhost Direct.</li><li>Under Name Resolution, enable hostname resolution through the proxy when appropriate.</li></ol><div class="rule-stack"><div><b>1 · Aether processes</b><em>DIRECT</em></div><div><b>2 · Selected applications</b><em>SOCKS5 127.0.0.1:1819</em></div><div><b>3 · Default</b><em>Your choice</em></div></div><p>Proxifier primarily handles TCP. UDP-only applications need a compatible TUN solution.</p>`},
    {id:'verify',title:'Verify proxied traffic',html:`<ol><li>Confirm the state is Connected.</li><li>Open Diagnostics and run Verify connection. A Cloudflare trace response confirms HTTPS succeeded through SOCKS5.</li><li>Check the client connection log and confirm the application matched the intended rule.</li><li>Enable remote/proxy DNS where available.</li><li>Disconnect Aether temporarily. A strictly proxied application should stop reaching the network if it has no direct fallback.</li></ol><aside><b>Use more than an IP check</b><p>A changed public IP does not prove DNS follows the proxy. Verify routing and DNS separately.</p></aside>`},
    {id:'updates',title:'Updating and security',html:`<ol><li>Open About and choose Check for updates.</li><li>Download only from the official hamvex/AetherGUI Releases page.</li><li>Disconnect and Exit from the tray.</li><li>Run the new Setup, launch the app, and verify the connection.</li></ol><p>Published Windows files are currently unsigned and can trigger SmartScreen. Compare their SHA-256 with <code>SHA256SUMS.txt</code>. TLS validation stays enabled, settings are never executed through a shell, and remote listeners require explicit acknowledgement.</p>`},
    {id:'faq',title:'FAQ and troubleshooting',html:`<details open><summary>Which settings should I try first?</summary><p>MASQUE, Balanced, IPv4, Firewall, and HTTP/3. Then try HTTP/2 and Thorough.</p></details><details><summary>Why does closing the window not exit?</summary><p>The app hides in the tray to preserve an active proxy. Use Tray → Exit.</p></details><details><summary>Scanning never completes</summary><p>Use IPv4 and Thorough, clear a custom endpoint, check firewall permissions, and make sure port 1819 is free.</p></details><details><summary>Connected, but an application has no internet</summary><p>Select SOCKS5—not HTTP—use the exact host and port, enable proxy DNS, and inspect routing rules.</p></details><details><summary>HTTP/3 fails</summary><p>Switch MASQUE to HTTP/2 because UDP/QUIC may be blocked.</p></details><details><summary>How do I report a problem?</summary><p>Copy Diagnostics logs, remove sensitive information, and include Windows version, protocol, transport, and scan mode.</p></details>`}
  ],
  fa: [
    {id:'introduction',title:'معرفی Aether',html:`<p>Aether با پیدا کردن endpointهای قابل‌استفادهٔ Cloudflare، از طریق MASQUE، ‏WireGuard یا gool یک پروکسی SOCKS5 محلی ایجاد می‌کند. Firstham AetherGui رابط ویندوزی هستهٔ رسمی Aether است؛ هسته را امن اجرا می‌کند، تنظیمات سازگار را می‌فرستد، وضعیت و لاگ را نمایش می‌دهد و پردازش را تمیز می‌بندد.</p><aside><b>پروکسی است، نه VPN سراسری</b><p>هر برنامه را روی <code>127.0.0.1:1819</code> تنظیم کنید یا ترافیک را با v2rayN یا Proxifier هدایت کنید.</p></aside>`},
    {id:'how',title:'Aether چگونه کار می‌کند؟',html:`<p>دکمهٔ اتصال ابتدا پروفایل را اعتبارسنجی و سپس <code>aether.exe</code> را به‌صورت پردازش فرزند مخفی اجرا می‌کند. Aether یک endpoint مناسب پیدا می‌کند، تونل انتخابی را می‌سازد و برای ترافیک SOCKS5 روی رایانه گوش می‌دهد.</p><div class="doc-flow"><span>برنامهٔ شما</span><i>←</i><b>SOCKS5<br><small>127.0.0.1:1819</small></b><i>←</i><span>تونل Aether</span><i>←</i><span>اینترنت</span></div><p>در صورت وجود، گزینهٔ Proxy DNS یا Remote DNS را در کلاینت فعال کنید تا DNS هم از همان مسیر عبور کند.</p>`},
    {id:'interface',title:'بخش‌های برنامه',html:`<ul><li><b>اتصال:</b> وضعیت، اتصال/قطع، endpoint، آدرس پروکسی، زمان و پروفایل جمع‌وجور.</li><li><b>تنظیمات پیشرفته:</b> حالت IP، مبهم‌سازی، شنونده، endpoint، timeout، گزینه‌های ایمنی و مسیر config.</li><li><b>عیب‌یابی:</b> بررسی اتصال، Cloudflare Trace و لاگ زندهٔ هسته.</li><li><b>راهنمای کاربر:</b> مستندات دوزبانه و قابل‌جست‌وجو.</li><li><b>درباره:</b> نسخه، منبع پروژه، به‌روزرسانی و تلگرام.</li><li><b>System Tray:</b> نمایش، اتصال، قطع و خروج. بستن پنجره اتصال فعال را قطع نمی‌کند.</li></ul>`},
    {id:'setup',title:'راه‌اندازی اولیه',html:`<ol><li>آخرین Setup نسخهٔ x64 را از Releases رسمی همین پروژه نصب کنید.</li><li>Firstham AetherGui را باز و زبان فارسی یا انگلیسی را انتخاب کنید.</li><li>گزینه‌های <b>MASQUE</b>، ‏<b>Balanced</b> و <b>HTTP/3</b> را نگه دارید.</li><li><b>اتصال</b> را بزنید و منتظر وضعیت متصل بمانید.</li><li>بخش <b>عیب‌یابی</b> را باز و بررسی اتصال را اجرا کنید.</li><li>در برنامهٔ مقصد SOCKS5 با میزبان <code>127.0.0.1</code> و پورت <code>1819</code> تنظیم کنید.</li></ol>`},
    {id:'states',title:'وضعیت‌های اتصال',html:`<div class="state-guide"><p><i class="state-dot disconnected"></i><b>قطع:</b> پروکسی اجرا نیست.</p><p><i class="state-dot scanning"></i><b>در حال اسکن:</b> جست‌وجوی endpoint سالم.</p><p><i class="state-dot connecting"></i><b>در حال اتصال:</b> مذاکرهٔ تونل.</p><p><i class="state-dot connected"></i><b>متصل:</b> SOCKS5 آماده است.</p><p><i class="state-dot reconnecting"></i><b>اتصال مجدد:</b> بازیابی مسیر قطع‌شده.</p><p><i class="state-dot error"></i><b>خطا:</b> عیب‌یابی را بررسی و پروفایل دیگری امتحان کنید.</p></div>`},
    {id:'protocols',title:'MASQUE، ‏WireGuard و gool',html:`<div class="doc-cards"><div><b>MASQUE · پیشنهادی</b><p>تونل مبتنی بر HTTP. با HTTP/3 شروع و هنگام مسدودبودن UDP از HTTP/2 استفاده کنید.</p></div><div><b>WireGuard</b><p>تونل سبک UDP که در شبکه‌های سازگار می‌تواند عملکرد خوبی داشته باشد.</p></div><div><b>gool</b><p>حالت WARP-in-WARP برای شبکه‌هایی که پروفایل‌های دیگر ناپایدارند.</p></div></div><p>هیچ پروتکلی در همهٔ شبکه‌ها بهترین نیست. پیش از ترک MASQUE، انتقال HTTP/2 را امتحان کنید.</p>`},
    {id:'transport',title:'مقایسهٔ HTTP/3 و HTTP/2',html:`<table><thead><tr><th></th><th>HTTP/3</th><th>HTTP/2</th></tr></thead><tbody><tr><th>انتقال</th><td>QUIC / UDP</td><td>TCP</td></tr><tr><th>انتخاب اول</th><td>بله</td><td>هنگام مشکل UDP</td></tr><tr><th>مقدار Aether</th><td><code>AETHER_MASQUE_HTTP2=0</code></td><td><code>AETHER_MASQUE_HTTP2=1</code></td></tr></tbody></table>`},
    {id:'scan',title:'حالت اسکن و IP',html:`<ul><li><b>Turbo:</b> سریع‌ترین کشف در شبکهٔ سالم.</li><li><b>Balanced:</b> تعادل پیشنهادی سرعت و پوشش.</li><li><b>Thorough:</b> جست‌وجوی گسترده‌تر و کندتر وقتی Balanced نتیجه ندارد.</li><li><b>Stealth:</b> الگوی محافظه‌کارانه برای شبکه‌های حساس.</li></ul><p>IPv4 گزینهٔ پیش‌فرض مطمئن است. IPv6 را فقط با IPv6 واقعی و پایدار انتخاب کنید؛ Both پوشش را بیشتر و اسکن را طولانی‌تر می‌کند.</p>`},
    {id:'obfuscation',title:'پروفایل‌های مبهم‌سازی',html:`<p>مبهم‌سازی الگوی قابل‌مشاهدهٔ ترافیک را تغییر می‌دهد. رابط فقط گزینه‌های معتبر پروتکل فعلی را نشان می‌دهد.</p><ul><li><b>MASQUE:</b> ‏Firewall (پیشنهادی)، ‏GFW، خاموش.</li><li><b>WireGuard و gool:</b> ‏Balanced (پیشنهادی)، ‏Aggressive، ‏Light، خاموش.</li></ul><p>حالت‌های Aggressive سربار بیشتری دارند؛ فقط هنگام شکست حالت پیشنهادی از آن‌ها استفاده کنید.</p>`},
    {id:'advanced',title:'تنظیمات پیشرفته و Watchdog',html:`<ul><li><b>شنوندهٔ SOCKS5:</b> مقدار <code>127.0.0.1:1819</code> را نگه دارید. آدرس غیرمحلی پروکسی را در معرض شبکه می‌گذارد.</li><li><b>Endpoint سفارشی:</b> مقدار دقیق <code>IP:port</code>؛ برای اسکن خالی بگذارید.</li><li><b>Keepalive:</b> فاصلهٔ keepalive وایرگارد؛ ۵ ثانیه پیشنهاد می‌شود.</li><li><b>مهلت توقف:</b> زمان تشخیص تلاش گیرکرده؛ ۹۰ ثانیه پیشنهاد می‌شود.</li><li><b>Watchdog:</b> هستهٔ گیرکرده را امن متوقف می‌کند؛ روشن بماند.</li><li><b>اتصال مجدد سریع:</b> ابتدا endpoint تأییدشدهٔ قبلی را امتحان می‌کند.</li><li><b>مسیرهای پیکربندی:</b> فایل‌های سازگار با Aether؛ رابط مسیر را ذخیره می‌کند، نه کلید خصوصی.</li></ul>`},
    {id:'environment',title:'متغیرهای محیطی',html:`<table><thead><tr><th>متغیر</th><th>تنظیم رابط</th></tr></thead><tbody><tr><td><code>AETHER_PROTOCOL</code></td><td>پروتکل</td></tr><tr><td><code>AETHER_SCAN</code></td><td>حالت اسکن</td></tr><tr><td><code>AETHER_IP</code></td><td>اسکن IP</td></tr><tr><td><code>AETHER_NOIZE</code></td><td>مبهم‌سازی</td></tr><tr><td><code>AETHER_SOCKS</code></td><td>شنوندهٔ SOCKS5</td></tr><tr><td><code>AETHER_MASQUE_HTTP2</code></td><td>انتقال MASQUE</td></tr><tr><td><code>AETHER_PEER / AETHER_WG_PEER</code></td><td>Endpoint سفارشی</td></tr><tr><td><code>AETHER_WG_KEEPALIVE</code></td><td>Keepalive</td></tr><tr><td><code>AETHER_QUICK_RECONNECT</code></td><td>اتصال سریع</td></tr><tr><td><code>AETHER_CONFIG</code></td><td>Config پایه</td></tr><tr><td><code>AETHER_WG_CONFIG</code></td><td>Config وایرگارد</td></tr><tr><td><code>AETHER_MASQUE_CONFIG</code></td><td>Config ‏MASQUE</td></tr></tbody></table>`},
    {id:'v2rayn',title:'تنظیم v2rayN',html:`<ol><li>Aether را متصل کنید و منتظر وضعیت متصل بمانید.</li><li>در v2rayN یک سرور یا پروفایل SOCKS اضافه کنید.</li><li>Remarks را <code>Aether</code>، آدرس را <code>127.0.0.1</code> و پورت را <code>1819</code> بگذارید؛ نام کاربری و رمز خالی باشد.</li><li>ذخیره و فعال کنید یا alias آن را به‌عنوان Front Proxy یک نود دیگر انتخاب کنید.</li><li>اگر TUN روشن است برای <code>aether-gui.exe</code> و <code>aether.exe</code> قانون Direct/bypass بسازید.</li></ol><div class="doc-route"><span>برنامه</span><i>←</i><span>v2rayN</span><i>←</i><b>Aether SOCKS5</b><i>←</i><span>اینترنت</span></div><aside><b>جلوگیری از حلقه</b><p>Aether را هم‌زمان ورودی و خروجی یک مسیر قرار ندهید.</p></aside>`},
    {id:'proxifier',title:'تنظیم Proxifier',html:`<ol><li>Aether را متصل کنید.</li><li>به <b>Profile → Proxy Servers → Add</b> بروید.</li><li>Address: <code>127.0.0.1</code>؛ Port: <code>1819</code>؛ Protocol: <b>SOCKS Version 5</b>؛ Authentication: خاموش.</li><li>Check را بزنید و ذخیره کنید.</li><li>در Proxification Rules یک قانون <b>Direct</b> در بالاترین جایگاه برای <code>aether-gui.exe; aether.exe</code> بسازید.</li><li>برنامه‌های دلخواه را پایین آن اضافه و پروکسی Aether را انتخاب کنید. Localhost باید Direct بماند.</li><li>در Name Resolution، در صورت نیاز resolve از طریق پروکسی را فعال کنید.</li></ol><div class="rule-stack"><div><b>۱ · پردازش‌های Aether</b><em>DIRECT</em></div><div><b>۲ · برنامه‌های منتخب</b><em>SOCKS5 127.0.0.1:1819</em></div><div><b>۳ · Default</b><em>انتخاب شما</em></div></div><p>Proxifier عمدتاً TCP را هدایت می‌کند؛ برنامه‌های فقط UDP به راهکار TUN سازگار نیاز دارند.</p>`},
    {id:'verify',title:'بررسی عبور ترافیک',html:`<ol><li>از وضعیت متصل مطمئن شوید.</li><li>در عیب‌یابی، بررسی اتصال را اجرا کنید. پاسخ Cloudflare Trace یعنی HTTPS از SOCKS5 عبور کرده است.</li><li>لاگ اتصال کلاینت را ببینید و تطبیق برنامه با Rule را تأیید کنید.</li><li>در صورت وجود، Proxy DNS یا Remote DNS را فعال کنید.</li><li>Aether را موقتاً قطع کنید. برنامه‌ای که fallback مستقیم ندارد باید دسترسی را از دست بدهد.</li></ol><aside><b>فقط IP کافی نیست</b><p>تغییر IP عمومی ثابت نمی‌کند DNS پروکسی شده است؛ مسیر و DNS را جداگانه بررسی کنید.</p></aside>`},
    {id:'updates',title:'به‌روزرسانی و امنیت',html:`<ol><li>در درباره، بررسی نسخهٔ جدید را انتخاب کنید.</li><li>فقط از Releases رسمی hamvex/AetherGUI دانلود کنید.</li><li>اتصال را قطع و از Tray کاملاً خارج شوید.</li><li>Setup جدید را اجرا، برنامه را باز و اتصال را بررسی کنید.</li></ol><p>فایل‌های فعلی ویندوز امضای تجاری ندارند و ممکن است SmartScreen هشدار دهد. SHA-256 را با <code>SHA256SUMS.txt</code> مقایسه کنید. اعتبارسنجی TLS روشن می‌ماند، تنظیمات در shell اجرا نمی‌شوند و شنوندهٔ غیرمحلی نیاز به تأیید صریح دارد.</p>`},
    {id:'faq',title:'پرسش‌های رایج و رفع اشکال',html:`<details open><summary>ابتدا چه تنظیماتی را امتحان کنم؟</summary><p>MASQUE، ‏Balanced، ‏IPv4، ‏Firewall و HTTP/3. سپس HTTP/2 و Thorough را امتحان کنید.</p></details><details><summary>چرا بستن پنجره برنامه را خارج نمی‌کند؟</summary><p>برنامه برای حفظ پروکسی در Tray مخفی می‌شود؛ از Tray → Exit استفاده کنید.</p></details><details><summary>اسکن تمام نمی‌شود</summary><p>IPv4 و Thorough را انتخاب، endpoint سفارشی را پاک، مجوز فایروال و آزادبودن پورت 1819 را بررسی کنید.</p></details><details><summary>متصل است ولی برنامه اینترنت ندارد</summary><p>SOCKS5—not HTTP—را انتخاب، آدرس و پورت را دقیق وارد، Proxy DNS را فعال و Ruleها را بررسی کنید.</p></details><details><summary>HTTP/3 کار نمی‌کند</summary><p>MASQUE را روی HTTP/2 بگذارید؛ احتمالاً UDP/QUIC محدود است.</p></details><details><summary>چگونه خطا گزارش کنم؟</summary><p>لاگ عیب‌یابی را کپی، اطلاعات حساس را حذف و نسخهٔ ویندوز، پروتکل، انتقال و حالت اسکن را ذکر کنید.</p></details>`}
  ]
};

const routingDocumentation = {
  en: {
    vpn:{id:'vpn-mode',title:'System-wide VPN Mode',html:`<p>VPN Mode starts Aether, verifies the SOCKS5 handshake, requests administrator permission for the narrowly scoped routing process, then starts the embedded sing-box TUN engine.</p><div class="doc-flow"><span>Windows apps</span><i>→</i><b>FirsthamAether TUN</b><i>→</i><span>sing-box</span><i>→</i><span>Aether SOCKS5</span><i>→</i><span>Internet</span></div><ul><li><b>Full Tunnel:</b> routes all supported IPv4 and IPv6 traffic.</li><li><b>Bypass Local Networks:</b> keeps private, loopback, and link-local destinations direct.</li><li><b>Split Tunnel:</b> includes or excludes exact executable paths using sing-box process matching.</li><li><b>DNS leak protection:</b> strict Windows routing intercepts DNS and resolves through encrypted DNS over Aether.</li><li><b>IPv6:</b> route it through Aether or explicitly reject it; it is never left as an uncontrolled bypass.</li><li><b>Kill Switch:</b> keeps the TUN route active when the upstream SOCKS5 path is unavailable. It is off by default.</li></ul><aside><b>Administrator permission</b><p>The interface remains unelevated. Windows only elevates the same verified application in helper mode to open the adapter and apply routes.</p></aside>`},
    intro:`<p>Aether discovers usable Cloudflare endpoints and creates a local SOCKS5 service through MASQUE, WireGuard, or gool. Firstham AetherGui adds an embedded Windows TUN routing layer, so the default VPN Mode routes applications without v2rayN, Proxifier, or manual proxy configuration.</p>`,
    setup:`<ol><li>Install the latest x64 Setup from GitHub Releases.</li><li>Launch the application and choose English or Persian.</li><li>Keep <b>System-wide VPN Mode</b>, <b>Bypass Local Networks</b>, MASQUE, Balanced, and HTTP/3.</li><li>Press <b>Connect</b> and approve the Windows elevation prompt for the routing helper.</li><li>Wait until Aether, the SOCKS5 handshake, TUN adapter, routes, protected DNS, and internet test are ready.</li><li>Open Diagnostics and run the network self-test. No companion proxy application is required.</li></ol>`,
    optional:`<p>v2rayN and Proxifier are not required. Advanced users may use them only as alternative diagnostic clients while <b>Manual SOCKS5</b> mode is selected. Configure <code>127.0.0.1:1819</code> and avoid creating a routing loop.</p>`
  },
  fa: {
    vpn:{id:'vpn-mode',title:'حالت VPN سراسری',html:`<p>حالت VPN ابتدا Aether را اجرا و handshake پروکسی SOCKS5 را بررسی می‌کند، سپس فقط برای پردازش محدود مسیریابی مجوز مدیر می‌خواهد و موتور TUN داخلی sing-box را اجرا می‌کند.</p><div class="doc-flow"><span>برنامه‌های ویندوز</span><i>←</i><b>TUN برنامه</b><i>←</i><span>sing-box</span><i>←</i><span>SOCKS5 ایثر</span><i>←</i><span>اینترنت</span></div><ul><li><b>تمام ترافیک:</b> ترافیک پشتیبانی‌شدهٔ IPv4 و IPv6 را عبور می‌دهد.</li><li><b>عبور مستقیم شبکه محلی:</b> مقصدهای خصوصی، loopback و link-local را مستقیم نگه می‌دارد.</li><li><b>تونل انتخابی:</b> مسیر دقیق فایل اجرایی را با تطبیق واقعی پردازش شامل یا مستثنی می‌کند.</li><li><b>محافظت نشت DNS:</b> DNS را در ویندوز رهگیری و به‌صورت رمزگذاری‌شده از Aether حل می‌کند.</li><li><b>IPv6:</b> یا از Aether عبور می‌کند یا صریحاً مسدود می‌شود؛ مسیر کنترل‌نشده ندارد.</li><li><b>قطع اضطراری:</b> هنگام از دسترس خارج‌شدن SOCKS5 مسیر TUN را بسته نگه می‌دارد و پیش‌فرض خاموش است.</li></ul><aside><b>مجوز مدیر</b><p>رابط کاربری عادی می‌ماند؛ ویندوز فقط همان برنامهٔ تأییدشده را در حالت helper برای رابط مجازی و routeها ارتقا می‌دهد.</p></aside>`},
    intro:`<p>Aether با MASQUE، ‏WireGuard یا gool یک سرویس SOCKS5 محلی ایجاد می‌کند. Firstham AetherGui یک لایهٔ TUN داخلی ویندوز اضافه می‌کند تا حالت پیش‌فرض VPN بدون v2rayN، ‏Proxifier یا تنظیم دستی پروکسی ترافیک را هدایت کند.</p>`,
    setup:`<ol><li>آخرین Setup نسخهٔ x64 را از GitHub Releases نصب کنید.</li><li>برنامه را باز و زبان فارسی یا انگلیسی را انتخاب کنید.</li><li><b>حالت VPN سراسری</b>، <b>عبور مستقیم شبکه محلی</b>، MASQUE، ‏Balanced و HTTP/3 را نگه دارید.</li><li><b>اتصال</b> را بزنید و درخواست مجوز ویندوز برای helper مسیریابی را تأیید کنید.</li><li>منتظر آماده‌شدن Aether، ‏SOCKS5، رابط TUN، routeها، DNS محافظت‌شده و تست اینترنت بمانید.</li><li>در عیب‌یابی، خودآزمایی شبکه را اجرا کنید. هیچ برنامهٔ جانبی لازم نیست.</li></ol>`,
    optional:`<p>v2rayN و Proxifier لازم نیستند. کاربران پیشرفته فقط برای عیب‌یابی جایگزین و در حالت <b>پروکسی SOCKS5 دستی</b> می‌توانند از آن‌ها با <code>127.0.0.1:1819</code> استفاده کنند؛ از ایجاد حلقهٔ مسیریابی جلوگیری کنید.</p>`
  }
};

for (const language of ['en','fa']) {
  const sections=docsByLanguage[language]; const copy=routingDocumentation[language];
  sections.splice(1,0,copy.vpn);
  sections.find(section=>section.id==='introduction').html=copy.intro;
  sections.find(section=>section.id==='setup').html=copy.setup;
  for (const id of ['v2rayn','proxifier']) { const section=sections.find(item=>item.id===id); section.title=(language==='fa'?'جایگزین اختیاری: ':'Optional alternative: ')+(id==='v2rayn'?'v2rayN':'Proxifier'); section.html=copy.optional; }
}
