export const translations = {
  en: {
    'nav.main':'Main navigation','nav.connection':'Connection','nav.diagnostics':'Diagnostics','nav.guide':'User guide','nav.about':'About','nav.tour':'Welcome tour',
    'language.label':'Language','language.ltr':'Left to right','language.rtl':'Right to left','dashboard.title':'Connection','dashboard.subtitle':'Start Aether and use its local proxy in your applications.',
    'status.disconnected':'Disconnected','status.scanning':'Scanning','status.connecting':'Connecting','status.connected':'Connected','status.reconnecting':'Reconnecting','status.error':'Error',
    'connection.label':'AETHER CONNECTION','connection.readyTitle':'Ready to connect','connection.readyMessage':'Recommended settings are selected.','connection.scanningTitle':'Finding an endpoint…','connection.scanningMessage':'Aether is testing available endpoints.','connection.connectingTitle':'Establishing the tunnel…','connection.connectingMessage':'A healthy endpoint was found.','connection.connectedTitle':'Proxy is ready','connection.connectedMessage':'Applications can now use the local SOCKS5 proxy.','connection.reconnectingTitle':'Restoring connection…','connection.reconnectingMessage':'Aether is trying the last verified route.','connection.errorTitle':'Connection needs attention','connection.errorMessage':'Review Diagnostics, then try another profile.',
    'actions.connect':'Connect','actions.disconnect':'Disconnect','actions.verify':'Verify','actions.verifyConnection':'Verify connection','actions.copy':'Copy','actions.reset':'Reset defaults','actions.copyLogs':'Copy logs','actions.clear':'Clear','actions.close':'Close','actions.back':'Back','actions.next':'Next','actions.start':'Start connecting',
    'facts.endpoint':'Endpoint','facts.proxy':'SOCKS5 proxy','facts.elapsed':'Elapsed','facts.notSelected':'Not selected',
    'proxy.title':'Local proxy','proxy.description':'Use these SOCKS5 details in v2rayN, Proxifier, or another application.',
    'settings.title':'Connection profile','settings.subtitle':'Three choices are usually all you need.','settings.protocol':'Protocol','settings.scan':'Scan mode','settings.transport':'MASQUE transport','settings.recommendedHint':'MASQUE, Balanced, and HTTP/3 are recommended for most users.','settings.ipMode':'IP scan','settings.obfuscation':'Obfuscation','settings.socks':'SOCKS5 listen address','settings.peer':'Custom endpoint','settings.allowRemote':'Allow a non-local listener','settings.keepalive':'WireGuard keepalive','settings.timeout':'Stall timeout','settings.watchdog':'Watchdog','settings.quickReconnect':'Quick reconnect','settings.baseConfig':'Base configuration','settings.wgConfig':'WireGuard configuration','settings.masqueConfig':'MASQUE configuration',
    'recommended.masque':'Recommended: MASQUE','common.recommended':'Recommended','advanced.title':'Advanced Settings','advanced.subtitle':'Network details, safety, and configuration files','advanced.network':'Network','advanced.reliability':'Reliability and safety','advanced.files':'Configuration files',
    'tooltip.protocol':'The tunnel technology Aether uses. MASQUE is the best starting point.','tooltip.scan':'Controls how quickly and thoroughly Aether searches for an endpoint.','tooltip.transport':'HTTP/3 uses UDP/QUIC. HTTP/2 uses TCP and can work when UDP is blocked.','tooltip.ipMode':'Selects the IP address families included in scanning.','tooltip.obfuscation':'Changes traffic patterns to improve reliability on filtered networks.','tooltip.socks':'The local address other applications use to reach Aether.','tooltip.peer':'Skips automatic discovery and uses a specific IP address and port.','tooltip.keepalive':'Seconds between WireGuard keepalive packets.','tooltip.timeout':'How long the GUI waits before treating a connection attempt as stuck.',
    'help.ipMode':'IPv4 is the safest default.','help.socks':'Keep this on localhost for normal use.','help.peer':'Recommended: leave empty.','help.allowRemote':'This can expose the proxy to other devices.','help.watchdog':'Stop a core process that becomes stuck.','help.quickReconnect':'Try the last verified endpoint first.','help.configFiles':'The GUI stores file paths, never keys or credentials.','help.obfuscationMasque':'Firewall is recommended for MASQUE.','help.obfuscationOther':'Balanced is recommended for this protocol.',
    'placeholder.peer':'Leave empty for automatic scan','placeholder.defaultPath':'Use application default','placeholder.optional':'Optional','unit.seconds':'seconds',
    'diagnostics.title':'Diagnostics','diagnostics.subtitle':"Verify the proxy or inspect Aether's live output.",'diagnostics.verifyTitle':'Connection check','diagnostics.verifyDescription':'Send an HTTPS request through the configured SOCKS5 proxy.','diagnostics.result':'Cloudflare trace result','diagnostics.logs':'Live logs','diagnostics.logsHelp':'Useful when a connection fails or stalls.','diagnostics.waiting':'Waiting for Aether…',
    'docs.title':'User guide','docs.subtitle':'Setup, concepts, proxy guides, and troubleshooting.','docs.search':'Search documentation','docs.sections':'Documentation sections','docs.noResults':'No matching sections found.','docs.contents':'Contents',
    'about.title':'About','about.subtitle':'Application details and project links.','about.description':'A compact Windows frontend for the official Aether networking core.','about.appVersion':'Application','about.coreVersion':'Aether core','about.platform':'Platform','about.basedOn':'Based on CluvexStudio/Aether','about.attribution':'The original Aether project remains the networking engine. This GUI is an additional frontend and does not replace the CLI.','about.viewUpstream':'View upstream project','about.telegram':'Join Telegram Channel','about.releases':'Check for updates',
    'wizard.welcomeLabel':'WELCOME','wizard.welcomeTitle':'Welcome to Firstham AetherGui','wizard.welcomeText':'A simple interface for Aether. Choose your language to begin.','wizard.basicsLabel':'THE BASICS','wizard.basicsTitle':'Aether creates a local proxy','wizard.basicsText':'Applications send traffic to Aether through SOCKS5, then Aether carries it through the selected tunnel.','wizard.apps':'Your apps','wizard.protocolLabel':'PROTOCOL','wizard.protocolTitle':'Start with MASQUE','wizard.protocolText':'MASQUE with HTTP/3 is recommended. Switch to HTTP/2 if UDP is blocked or unreliable.','wizard.scanLabel':'SCAN MODE','wizard.scanTitle':'Balanced is the best default','wizard.scanText':'Balanced combines quick discovery with dependable coverage. Try Thorough only if it cannot find an endpoint.','wizard.readyLabel':'READY','wizard.readyTitle':'Connect, then verify','wizard.readyText':'Press Connect, wait for the green Connected state, then verify the proxy from Diagnostics.',
    'scan.turbo':'Turbo — fastest','scan.balanced':'Balanced — recommended','scan.thorough':'Thorough — wider search','scan.stealth':'Stealth — conservative','ip.v4':'IPv4 — recommended','ip.v6':'IPv6 only','ip.both':'IPv4 + IPv6','obfuscation.firewall':'Firewall — recommended','obfuscation.gfw':'GFW','obfuscation.balanced':'Balanced — recommended','obfuscation.aggressive':'Aggressive','obfuscation.light':'Light','obfuscation.off':'Off',
    'toast.defaults':'Recommended defaults restored.','toast.proxyCopied':'Proxy address copied.','toast.logsCopied':'Logs copied.','toast.verified':'Connection verified through Aether.','toast.languageSaved':'Language saved.','toast.error':'Something went wrong.','toast.invalidAddress':'Enter a valid IP address and port.','toast.portInUse':'The SOCKS5 port may already be in use.','toast.connectionFailed':'Connection failed. Review Diagnostics and try another profile.'
  },
  fa: {
    'nav.main':'پیمایش اصلی','nav.connection':'اتصال','nav.diagnostics':'عیب‌یابی','nav.guide':'راهنمای کاربر','nav.about':'درباره','nav.tour':'راهنمای شروع',
    'language.label':'زبان','language.ltr':'چپ به راست','language.rtl':'راست به چپ','dashboard.title':'اتصال','dashboard.subtitle':'Aether را اجرا کنید و از پروکسی محلی آن در برنامه‌ها استفاده کنید.',
    'status.disconnected':'قطع','status.scanning':'در حال اسکن','status.connecting':'در حال اتصال','status.connected':'متصل','status.reconnecting':'اتصال مجدد','status.error':'خطا',
    'connection.label':'اتصال AETHER','connection.readyTitle':'آمادهٔ اتصال','connection.readyMessage':'تنظیمات پیشنهادی انتخاب شده‌اند.','connection.scanningTitle':'در حال یافتن endpoint…','connection.scanningMessage':'Aether در حال بررسی endpointهای موجود است.','connection.connectingTitle':'در حال ساخت تونل…','connection.connectingMessage':'یک endpoint سالم پیدا شد.','connection.connectedTitle':'پروکسی آماده است','connection.connectedMessage':'برنامه‌ها اکنون می‌توانند از پروکسی SOCKS5 محلی استفاده کنند.','connection.reconnectingTitle':'در حال بازیابی اتصال…','connection.reconnectingMessage':'Aether مسیر تأییدشدهٔ قبلی را امتحان می‌کند.','connection.errorTitle':'اتصال نیاز به بررسی دارد','connection.errorMessage':'بخش عیب‌یابی را بررسی و پروفایل دیگری امتحان کنید.',
    'actions.connect':'اتصال','actions.disconnect':'قطع اتصال','actions.verify':'بررسی','actions.verifyConnection':'بررسی اتصال','actions.copy':'کپی','actions.reset':'بازنشانی','actions.copyLogs':'کپی لاگ‌ها','actions.clear':'پاک‌کردن','actions.close':'بستن','actions.back':'قبلی','actions.next':'بعدی','actions.start':'شروع اتصال',
    'facts.endpoint':'نقطهٔ پایانی','facts.proxy':'پروکسی SOCKS5','facts.elapsed':'زمان اتصال','facts.notSelected':'انتخاب نشده',
    'proxy.title':'پروکسی محلی','proxy.description':'این مشخصات SOCKS5 را در v2rayN، ‏Proxifier یا برنامه‌های دیگر وارد کنید.',
    'settings.title':'پروفایل اتصال','settings.subtitle':'معمولاً همین سه انتخاب کافی است.','settings.protocol':'پروتکل','settings.scan':'حالت اسکن','settings.transport':'انتقال MASQUE','settings.recommendedHint':'برای بیشتر کاربران MASQUE، ‏Balanced و HTTP/3 پیشنهاد می‌شود.','settings.ipMode':'اسکن IP','settings.obfuscation':'مبهم‌سازی','settings.socks':'آدرس شنوندهٔ SOCKS5','settings.peer':'Endpoint سفارشی','settings.allowRemote':'اجازهٔ شنوندهٔ غیرمحلی','settings.keepalive':'Keepalive وایرگارد','settings.timeout':'مهلت توقف','settings.watchdog':'Watchdog','settings.quickReconnect':'اتصال مجدد سریع','settings.baseConfig':'پیکربندی پایه','settings.wgConfig':'پیکربندی WireGuard','settings.masqueConfig':'پیکربندی MASQUE',
    'recommended.masque':'پیشنهادی: MASQUE','common.recommended':'پیشنهادی','advanced.title':'تنظیمات پیشرفته','advanced.subtitle':'جزئیات شبکه، ایمنی و فایل‌های پیکربندی','advanced.network':'شبکه','advanced.reliability':'پایداری و ایمنی','advanced.files':'فایل‌های پیکربندی',
    'tooltip.protocol':'فناوری تونلی که Aether استفاده می‌کند. MASQUE بهترین گزینه برای شروع است.','tooltip.scan':'سرعت و گستردگی جست‌وجوی endpoint مناسب را تعیین می‌کند.','tooltip.transport':'HTTP/3 از UDP/QUIC استفاده می‌کند. HTTP/2 مبتنی بر TCP است و هنگام مسدودبودن UDP می‌تواند کار کند.','tooltip.ipMode':'خانواده‌های آدرس IP مورد استفاده در اسکن را تعیین می‌کند.','tooltip.obfuscation':'الگوی ترافیک را برای پایداری بیشتر در شبکه‌های فیلترشده تغییر می‌دهد.','tooltip.socks':'آدرس محلی‌ای که برنامه‌های دیگر برای دسترسی به Aether استفاده می‌کنند.','tooltip.peer':'جست‌وجوی خودکار را رد می‌کند و از IP و پورت مشخص استفاده می‌کند.','tooltip.keepalive':'فاصلهٔ بسته‌های keepalive وایرگارد برحسب ثانیه.','tooltip.timeout':'مدتی که رابط پیش از گیرکرده دانستن تلاش اتصال صبر می‌کند.',
    'help.ipMode':'IPv4 مطمئن‌ترین گزینهٔ پیش‌فرض است.','help.socks':'برای استفادهٔ معمول این آدرس را روی localhost نگه دارید.','help.peer':'پیشنهاد: خالی بگذارید.','help.allowRemote':'این گزینه می‌تواند پروکسی را در معرض دستگاه‌های دیگر قرار دهد.','help.watchdog':'پردازش هسته‌ای را که گیر کرده متوقف می‌کند.','help.quickReconnect':'ابتدا آخرین endpoint تأییدشده را امتحان می‌کند.','help.configFiles':'رابط فقط مسیر فایل‌ها را ذخیره می‌کند، نه کلید یا اطلاعات ورود.','help.obfuscationMasque':'برای MASQUE حالت Firewall پیشنهاد می‌شود.','help.obfuscationOther':'برای این پروتکل حالت Balanced پیشنهاد می‌شود.',
    'placeholder.peer':'برای اسکن خودکار خالی بگذارید','placeholder.defaultPath':'استفاده از مسیر پیش‌فرض برنامه','placeholder.optional':'اختیاری','unit.seconds':'ثانیه',
    'diagnostics.title':'عیب‌یابی','diagnostics.subtitle':'پروکسی را بررسی کنید یا خروجی زندهٔ Aether را ببینید.','diagnostics.verifyTitle':'بررسی اتصال','diagnostics.verifyDescription':'یک درخواست HTTPS از طریق پروکسی SOCKS5 تنظیم‌شده ارسال می‌کند.','diagnostics.result':'نتیجهٔ Cloudflare Trace','diagnostics.logs':'لاگ‌های زنده','diagnostics.logsHelp':'برای بررسی شکست یا توقف اتصال کاربرد دارد.','diagnostics.waiting':'در انتظار Aether…',
    'docs.title':'راهنمای کاربر','docs.subtitle':'راه‌اندازی، مفاهیم، تنظیم پروکسی و رفع اشکال.','docs.search':'جست‌وجو در راهنما','docs.sections':'بخش‌های راهنما','docs.noResults':'بخشی مطابق جست‌وجو پیدا نشد.','docs.contents':'فهرست',
    'about.title':'درباره','about.subtitle':'مشخصات برنامه و پیوندهای پروژه.','about.description':'رابط جمع‌وجور ویندوز برای هستهٔ رسمی شبکهٔ Aether.','about.appVersion':'برنامه','about.coreVersion':'هستهٔ Aether','about.platform':'سیستم‌عامل','about.basedOn':'بر پایهٔ CluvexStudio/Aether','about.attribution':'پروژهٔ اصلی Aether همچنان موتور شبکه است. این رابط یک frontend اضافی است و جایگزین CLI نمی‌شود.','about.viewUpstream':'مشاهدهٔ پروژهٔ اصلی','about.telegram':'عضویت در کانال تلگرام','about.releases':'بررسی نسخهٔ جدید',
    'wizard.welcomeLabel':'خوش آمدید','wizard.welcomeTitle':'به Firstham AetherGui خوش آمدید','wizard.welcomeText':'یک رابط ساده برای Aether. برای شروع زبان را انتخاب کنید.','wizard.basicsLabel':'مفاهیم پایه','wizard.basicsTitle':'Aether یک پروکسی محلی می‌سازد','wizard.basicsText':'برنامه‌ها ترافیک را با SOCKS5 به Aether می‌فرستند و Aether آن را از تونل انتخابی عبور می‌دهد.','wizard.apps':'برنامه‌های شما','wizard.protocolLabel':'پروتکل','wizard.protocolTitle':'با MASQUE شروع کنید','wizard.protocolText':'MASQUE با HTTP/3 پیشنهاد می‌شود. اگر UDP مسدود یا ناپایدار است HTTP/2 را امتحان کنید.','wizard.scanLabel':'حالت اسکن','wizard.scanTitle':'Balanced بهترین پیش‌فرض است','wizard.scanText':'Balanced سرعت مناسب و پوشش قابل‌اعتماد دارد. اگر endpoint پیدا نشد Thorough را امتحان کنید.','wizard.readyLabel':'آماده','wizard.readyTitle':'متصل شوید و بررسی کنید','wizard.readyText':'اتصال را بزنید، منتظر وضعیت سبز متصل بمانید و سپس پروکسی را از بخش عیب‌یابی بررسی کنید.',
    'scan.turbo':'Turbo — سریع‌ترین','scan.balanced':'Balanced — پیشنهادی','scan.thorough':'Thorough — جست‌وجوی گسترده','scan.stealth':'Stealth — محافظه‌کارانه','ip.v4':'IPv4 — پیشنهادی','ip.v6':'فقط IPv6','ip.both':'IPv4 + IPv6','obfuscation.firewall':'Firewall — پیشنهادی','obfuscation.gfw':'GFW','obfuscation.balanced':'Balanced — پیشنهادی','obfuscation.aggressive':'Aggressive','obfuscation.light':'Light','obfuscation.off':'خاموش',
    'toast.defaults':'تنظیمات پیشنهادی بازنشانی شد.','toast.proxyCopied':'آدرس پروکسی کپی شد.','toast.logsCopied':'لاگ‌ها کپی شدند.','toast.verified':'اتصال از طریق Aether تأیید شد.','toast.languageSaved':'زبان ذخیره شد.','toast.error':'خطایی رخ داد.','toast.invalidAddress':'یک IP و پورت معتبر وارد کنید.','toast.portInUse':'ممکن است پورت SOCKS5 توسط برنامهٔ دیگری استفاده شود.','toast.connectionFailed':'اتصال ناموفق بود. بخش عیب‌یابی را بررسی و پروفایل دیگری امتحان کنید.'
  }
};

let currentLanguage = 'en';

export function setCurrentLanguage(language) {
  currentLanguage = language === 'fa' ? 'fa' : 'en';
  document.documentElement.lang = currentLanguage;
  document.documentElement.dir = currentLanguage === 'fa' ? 'rtl' : 'ltr';
  document.body.classList.toggle('rtl', currentLanguage === 'fa');
}

export function getCurrentLanguage() { return currentLanguage; }

export function t(key, language = currentLanguage) {
  return translations[language]?.[key] ?? translations.en[key] ?? key;
}

export function applyTranslations(root = document) {
  root.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); });
  root.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = t(element.dataset.i18nPlaceholder); });
  root.querySelectorAll('[data-i18n-tooltip]').forEach(element => { const value = t(element.dataset.i18nTooltip); element.dataset.tooltip = value; element.title = value; element.setAttribute('aria-label', value); });
  root.querySelectorAll('[data-i18n-aria]').forEach(element => { element.setAttribute('aria-label', t(element.dataset.i18nAria)); });
}
